// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SayyohlikA.Models;

#nullable disable

namespace SayyohlikA.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20251208113926_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SayyohlikA.Models.Davlat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nomi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Davlatlar");
                });

            modelBuilder.Entity("SayyohlikA.Models.Shahar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DavlatId")
                        .HasColumnType("integer");

                    b.Property<string>("Nomi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DavlatId");

                    b.ToTable("Shaharlar");
                });

            modelBuilder.Entity("Xaridor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DavlatId")
                        .HasColumnType("integer");

                    b.Property<string>("FIO")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ShaharId")
                        .HasColumnType("integer");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("TugilganSana")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("YaratilganVaqt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DavlatId");

                    b.HasIndex("ShaharId");

                    b.ToTable("Xaridorlar");
                });

            modelBuilder.Entity("SayyohlikA.Models.Shahar", b =>
                {
                    b.HasOne("SayyohlikA.Models.Davlat", "Davlat")
                        .WithMany("Shaharlar")
                        .HasForeignKey("DavlatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Davlat");
                });

            modelBuilder.Entity("Xaridor", b =>
                {
                    b.HasOne("SayyohlikA.Models.Davlat", "Davlat")
                        .WithMany()
                        .HasForeignKey("DavlatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SayyohlikA.Models.Shahar", "Shahar")
                        .WithMany()
                        .HasForeignKey("ShaharId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Davlat");

                    b.Navigation("Shahar");
                });

            modelBuilder.Entity("SayyohlikA.Models.Davlat", b =>
                {
                    b.Navigation("Shaharlar");
                });
#pragma warning restore 612, 618
        }
    }
}
